name: Codespell PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  codespell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Codespell
        uses: codespell-project/actions-codespell@v2
        with:
          ignore_words_file: .codespell_ignore